version: "3.9"

volumes:
  postgres-data: {}
  solr-data: {}
  ckan-filestore: {}
  datapusher-db: {}

services:
  web:
    build: .
    depends_on:
        - db
        - solr
        - redis
    ports:
        - "8080:8080"
    env_file:
      - .env
    command: uwsgi -i /ckan-uwsgi.ini
    volumes:
      - ./ckan.ini:/ckan.ini
      - ./contrib/ckan/ckan-uwsgi.ini:/ckan-uwsgi.ini
      - ./contrib/ckan/ckan-wsgi.py:/ckan-wsgi.py
      - ckan-filestore:/var/lib/ckan/default
  
  # ckan_gather_consumer:
  #   build: .
  #   depends_on:
  #       - db
  #       - solr
  #       - redis
  #   env_file:
  #     - .env
  #   command: paster --plugin=ckanext-harvest harvester gather_consumer --config=/ckan.ini
  #   volumes:
  #     - ./ckan.ini:/ckan.ini
  #     - ckan-filestore:/var/lib/ckan/default
  
  datapusher:
    build: contrib/ckan-datapusher
    depends_on:
      - web
    # command: uwsgi -i /datapusher-uwsgi.ini
    volumes: 
      - ./contrib/ckan-datapusher/datapusher-uwsgi.ini:/datapusher-uwsgi.ini
    
  
  db:
    build: contrib/postgresql
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=ckan_default
      - POSTGRES_PASSWORD=pass
      - DATASTORE_READONLY_PASS=pass
      - PGUSER=ckan_default
      - PGPASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  solr:
    image: cwradvocacy/ckan-solr:2.9.2
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/ckan

  redis:
    image: redis:6.2.1
  
