version: "3.9"

volumes:
  postgres-data: {}
  solr-data: {}
  ckan-filestore: {}

services:
  web:
    build: .
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "8080:8080"
      - "5000:5000"
    entrypoint: /ckan-dev-entrypoint.sh
    command: ["uwsgi", "-i", "/ckan-uwsgi.ini", "-l", "40"]
    env_file:
      - .env
    volumes:
      - ./ckan.ini:/ckan.ini
      - ./contrib/ckan/ckan-dev-uwsgi.ini:/ckan-uwsgi.ini
      - ./contrib/ckan/ckan-dev-entrypoint.sh:/ckan-dev-entrypoint.sh
      - ./contrib/ckan/ckan-entrypoint.sh:/ckan-entrypoint.sh
      - ./ckanext-genderopendata:/src/ckanext-genderopendata
      - ${CKANEXT_S3FILESTORE_DIR}:/src/ckanext-s3filestore
      - ckan-filestore:/var/lib/ckan/default
    sysctls:
      net.core.somaxconn: 1024

  datapusher:
    build: contrib/ckan-datapusher
    depends_on:
      - web
  
  db:
    build: contrib/postgresql
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=ckan_default
      - POSTGRES_PASSWORD=pass
      - DATASTORE_READONLY_PASS=pass
      - PGUSER=ckan_default
      - PGPASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  solr:
    image: cwradvocacy/ckan-solr:${CKAN_VERSION}
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr/data/ckan

  redis:
    image: redis:6.2.7
  
