version: "3.8"

volumes:
  postgres-data: {}
  solr-data: {}
  ckan-filestore: {}
  redis-data: {}

services:
  web:
    build:
      context: .
      target: dev
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "8080:8080"
      - "5000:5000"
    command: ["ckan", "-c", "/ckan.ini", "run", "--host", "0.0.0.0", "-t"]
    env_file:
      - .env
    volumes:
      - ./ckan-dev.ini:/ckan.ini
      - ./contrib/ckan/ckan-uwsgi.ini:/ckan-uwsgi.ini
      - ./contrib/ckan/ckan-entrypoint.sh:/ckan-entrypoint.sh
      - ./ckanext-genderopendata:/src/ckanext-genderopendata
      - ${CKANEXT_S3FILESTORE_DIR}:/src/ckanext-s3filestore
      - ckan-filestore:/var/lib/ckan/default
      - ${CKANEXT_SENTRY_DIR}:/src/ckanext-sentry
    sysctls:
      net.core.somaxconn: 65536

  datapusher:
    build: contrib/ckan-datapusher
    depends_on:
      - web
    environment:
      - JOB_CONFIG=/src/datapusher/deployment/datapusher_settings_dev.py
    ports:
      - "8800:8800"
    command: ["python", "/src/datapusher/datapusher/main.py", "/src/datapusher/deployment/datapusher_settings_dev.py"]
  
  db:
    build: contrib/postgresql
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=ckan_default
      - POSTGRES_PASSWORD=pass
      - DATASTORE_READONLY_PASS=pass
      - PGUSER=ckan_default
      - PGPASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  solr:
    image: ckan/ckan-solr:2.10-solr9-spatial
    shm_size: '1g'
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    image: redis:7
    platform: linux/arm64/v8
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
  
