set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE datastore_readonly NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATASTORE_READONLY_PASS';
    CREATE DATABASE datastore OWNER ckan_default ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE datastore TO ckan_default;
EOSQL
